### ISSUE TITLE
mechanical z-stage

### ISSUE THREAD

**Issue by Feanor007** [openUC2/UC2-GIT#80]
Hi all, it seems the inventor file for the mechanical z-stage is no longer available.
Does anyone know where to find it?

**Comment by beniroquai** [comment]
Hey @Feanor007 good point. All a bit confusing a bit with the stages since they developed faster than expected. Would you mind which stage you're looking for? With motors? Which motor? (Nema/28BYI?) Flexure based or with linear bearing from CNC machines? 
I guess we should have a separate Github repo for a stable version of the stage!

**Comment by Feanor007** [comment]
https://github.com/openUC2/UC2-GIT/tree/v3/CAD/ASSEMBLY_CUBE_Z-STAGE_mechanical
I was referring to this one, without motor

**Comment by beniroquai** [comment]
Hey @Feanor007, sorry for late reply. 
I just updated the RAW IPT files. You can find them [here](https://github.com/openUC2/UC2-GIT/tree/master/CAD/RAW/IPT)
